"""add phone and telegram_chat_id to users

Revision ID: 5ef0d5e9fc4d
Revises: bb9232e3ea58
Create Date: 2026-06-18 16:49:49.531601
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ef0d5e9fc4d'
down_revision: Union[str, None] = 'bb9232e3ea58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone', sa.String(), nullable=True))
    op.add_column('users', sa.Column('telegram_chat_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'telegram_chat_id')
    op.drop_column('users', 'phone')
    # ### end Alembic commands ###
