"""add foreign key constraints

Revision ID: 629d17a0fa91
Revises: 3d02fa71bbfc
Create Date: 2026-06-19 11:11:28.890647
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '629d17a0fa91'
down_revision: Union[str, None] = '3d02fa71bbfc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ai_agents', 'tenant_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.create_foreign_key(None, 'ai_agents', 'tenants', ['tenant_id'], ['id'])
    op.alter_column('conversations', 'tenant_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('conversations', 'ai_agent_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('conversations', 'customer_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.create_foreign_key(None, 'conversations', 'ai_agents', ['ai_agent_id'], ['id'])
    op.create_foreign_key(None, 'conversations', 'tenants', ['tenant_id'], ['id'])
    op.create_foreign_key(None, 'conversations', 'customers', ['customer_id'], ['id'])
    op.alter_column('customers', 'tenant_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.create_foreign_key(None, 'customers', 'tenants', ['tenant_id'], ['id'])
    op.alter_column('invoices', 'tenant_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.create_foreign_key(None, 'invoices', 'subscriptions', ['subscription_id'], ['id'])
    op.create_foreign_key(None, 'invoices', 'tenants', ['tenant_id'], ['id'])
    op.alter_column('messages', 'conversation_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.create_foreign_key(None, 'messages', 'conversations', ['conversation_id'], ['id'])
    op.alter_column('subscriptions', 'tenant_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('subscriptions', 'plan_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.create_foreign_key(None, 'subscriptions', 'tenants', ['tenant_id'], ['id'])
    op.create_foreign_key(None, 'subscriptions', 'plans', ['plan_id'], ['id'])
    op.create_foreign_key(None, 'users', 'tenants', ['tenant_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'subscriptions', type_='foreignkey')
    op.drop_constraint(None, 'subscriptions', type_='foreignkey')
    op.alter_column('subscriptions', 'plan_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('subscriptions', 'tenant_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.alter_column('messages', 'conversation_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(None, 'invoices', type_='foreignkey')
    op.drop_constraint(None, 'invoices', type_='foreignkey')
    op.alter_column('invoices', 'tenant_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(None, 'customers', type_='foreignkey')
    op.alter_column('customers', 'tenant_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    op.alter_column('conversations', 'customer_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('conversations', 'ai_agent_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('conversations', 'tenant_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(None, 'ai_agents', type_='foreignkey')
    op.alter_column('ai_agents', 'tenant_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
